allow security protocol ssl
Missing openssl on installation causing
> Fatal error: Uncaught RdKafka\Exception: Invalid value "ssl" for configuration property "security.protocol"
https://stackoverflow.com/a/59320037